Repository spyder-ide/spyder-unittest, pull requests merged in 2020-04, with the labels that each got.

#139 Fix TextEditor constructor
  spyder_unittest/widgets/unittestgui.py
Labels: type:bug, v0.4.1

#143 Move CI to GitHub actions
  .circleci/config.yml
  .github/workflows/linux-tests.yml
  .github/workflows/macos-tests.yml
  .github/workflows/windows-tests.yml
  README.md
  codecov.yml
  continuous_integration/circle/coverage.sh
  continuous_integration/circle/install.sh
  continuous_integration/circle/run_tests.sh
  requirements/tests.txt
Labels: type:task, v0.4.1

#144 Dynamic sizing of text editor window
  spyder_unittest/widgets/unittestgui.py
Labels: type:bug, v0.4.1

#141 Fix status label
  spyder_unittest/backend/pytestrunner.py
  spyder_unittest/backend/runnerbase.py
  spyder_unittest/backend/unittestrunner.py
  spyder_unittest/widgets/tests/test_unittestgui.py
  spyder_unittest/widgets/unittestgui.py
Labels: v0.4.1

#147 Fix abbreviator if name has parameters with dots
  spyder_unittest/backend/abbreviator.py
  spyder_unittest/backend/tests/test_abbreviator.py
Labels: type:bug, v0.4.1

#148 Use set_status_label function
  spyder_unittest/widgets/unittestgui.py
Labels: type:techdebt, v0.4.1

#151 Fix pytest backend
  spyder_unittest/backend/pytestrunner.py
  spyder_unittest/backend/pytestworker.py
  spyder_unittest/backend/tests/test_pytestrunner.py
  spyder_unittest/backend/tests/test_pytestworker.py
  spyder_unittest/widgets/tests/test_unittestgui.py
Labels: type:bug, v0.4.1
