Repository spyder-ide/spyder-unittest, pull requests merged in 2020-05, with the labels that each got.

#149 Fix pytest test filename path resolution
  spyder_unittest/backend/pytestrunner.py
  spyder_unittest/backend/pytestworker.py
  spyder_unittest/backend/tests/test_pytestrunner.py
  spyder_unittest/backend/tests/test_pytestworker.py
Labels: type:bug, v0.4.1

#150 Fix test_pytestrunner_start
  spyder_unittest/backend/runnerbase.py
  spyder_unittest/backend/tests/test_pytestrunner.py
  spyder_unittest/backend/tests/test_runnerbase.py
  spyder_unittest/widgets/unittestgui.py
Labels: type:techdebt, v0.4.1

#152 Fix pytest output processing
  spyder_unittest/backend/pytestrunner.py
  spyder_unittest/backend/tests/test_pytestrunner.py
Labels: type:techdebt, v0.4.1

#153 Fix tests that could never fail
  spyder_unittest/widgets/tests/test_unittestgui.py
Labels: type:techdebt, v0.4.1

#155 PR: Require Python 3.5 or later
  setup.py
  spyder_unittest/unittestplugin.py
  spyder_unittest/widgets/unittestgui.py
Labels: type:task, v0.4.1
